name: 5n_PLUS_1_SumOfDigits-2025-01-13

on:
  workflow_dispatch:
    inputs:
      n:
        description: '합성 횟수'
        required: True
        default: '10'
        type: string

run-name: 5n_PLUS_1_SumOfDigits-2025-01-13 [${{ github.event.inputs.n || '10' }}]

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run Python script
      run: python 5n_plus_1.py ${{ github.event.inputs.n || '10' }}
